### PR TITLE
Changed the transition to "fade"

### PR DESCRIPTION
**Pull request by deanwampler**
I think the cube rotation for transitioning between slides is cute at first, but quickly becomes an irritating distraction. So, this pull request changes it to the much less obnoxious "fade" transition.

### CODE REVIEW

**Comment by hseeberger** [comment]
Dean, we can't change the reveal.js code, because we have forked from the reveal.js repo and are constantly updating (rebasing) our stuff on top of it. Hence I suggest you look for a way to change the transitioning at the "client site".

**Comment by lutzh** [comment]
@deanwampler as a quick fix, you might want to change line 2882 of your local copy of index.html
    transition: Reveal.getQueryHash().transition || 'default', // default/cube/page/concave/zoom/linear/fade/none

If you replace "default" with "fade", you should be fine.
I'm not sure if everybody is going to be happy with fade. Also, I would like to keep it in line with the other courses. Is it ok if we leave it on default in the repo?

**Comment by deanwampler** [comment]
I guess my real point is that we change all of them to not use cube
rotations. Really bad visual experience for.every.single.slide. Not what
reveal.js should be using by default, IMHO.

I'll change my local copy for next week.

dean

On Wed, Jul 9, 2014 at 10:23 AM, Lutz Hühnken notifications@github.com
wrote:

> @deanwampler https://github.com/deanwampler as a quick fix, you might
> want to change line 2882 of your local copy of index.html
> transition: Reveal.getQueryHash().transition || 'default', //
> default/cube/page/concave/zoom/linear/fade/none
> 
> If you replace "default" with "fade", you should be fine.
> I'm not sure if everybody is going to be happy with fade. Also, I would
> like to keep it in line with the other courses. Is it ok if we leave it on
> default in the repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/typesafe-training/reveal.js/pull/1#issuecomment-48477523
> .

## 

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com

**Comment by hseeberger** [comment]
I like using defaults and I like this default; unless others share @deanwampler's opinion **and** a majority settles on an alternative, let's stick to the default.

**Comment by lutzh** [comment]
@deanwampler @hseeberger I have a feeling there won't be a consensus, plus, it's super-easy to override (either change that one line locally, or just add query parameter, e.g. "https://training.typesafe.com/20140716-as-dwampler/index.html?transition=fade#/"). Thus I agree with Heiko, let's just leave it as it is.
Maybe add info on how to override to instructor's notes.

**Comment by markusjura** [comment]
Transition has changed to 'none'.

**Pull request closed without merging**
